# -*- coding: utf-8 -*-
"""SmsSpamDetector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17f18C76L-uYu91INENZQLHH_JTNHfCUE
"""

#Load the data
from google.colab import files
uploaded = files.upload()

from __future__ import print_function, division
from future.utils import iteritems 
from builtins import range
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from wordcloud import WordCloud

df = pd.read_csv('spam.csv', encoding = 'ISO-8859-1')

df = df.drop(["Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], axis = 1)

df.columns = ['labels', 'data']

df['b_labels'] = df['labels'].map({'ham': 0, 'spam': 1})
Y = df['b_labels'].as_matrix()

count_vectorizer = CountVectorizer(decode_error = 'ignore')
X = count_vectorizer.fit_transform(df['data'])

Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size = 0.33)

model = MultinomialNB()
model.fit(Xtrain, Ytrain)

print("train score: ", model.score(Xtrain, Ytrain))

print("test score: ", model.score(Xtest, Ytest))

def visualize(label):
  words = ''
  for msg in df[df['labels'] == label]['data']:
    msg = msg.lower()
    words += msg + ' '
  wordcloud = WordCloud(width=600, height = 400).generate(words)
  plt.imshow(wordcloud)
  plt.axis('off')
  plt.show()

visualize('spam')

visualize('ham')

df['predictions'] = model.predict(X)

sneaky_spam = df[(df['predictions'] == 0) & (df['b_labels'] == 1)]['data']
for msg in sneaky_spam:
  print(msg)

not_actually_spam = df[(df['predictions'] == 1) & (df['b_labels'] == 0)]['data']
for msg in not_actually_spam:
  print(msg)
